name: CI

on:
  workflow_call:

jobs:
  auto-approve:
    if: contains(github.event_name, 'pull_request')
    runs-on: ubuntu-latest
    needs: []
    steps:
    - name: Auto Approve PR
      uses: actions/github-script@v7
      with:
       github-token: ${{ github.token }}
       script: |
        github.rest.pulls.createReview({
          owner: context.repo.owner,
          repo: context.repo.repo,
          pull_number: context.issue.number,
          event: "APPROVE"
        })
