name: attest

on:
  workflow_call:

jobs:
  attest:
    if:  contains(github.ref, 'main')
    name: attest
    runs-on: ubuntu-latest
    needs: []
    permissions:
      attestations: write
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/attest-build-provenance@v2
        with:
          subject-path: '*.tf'
