name: security

on:
  workflow_call:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
      security-events: write
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up Python 3.11
        uses: actions/setup-python@v6
        with:
          python-version: 3.11
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          download_external_modules: true
          framework: terraform
          quiet: true
          soft_fail: true
          output_format: cli,sarif
          output_file_path: console,results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v4
        if: success() || failure()
        with:
          sarif_file: results.sarif