name: security

on:
  workflow_call:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    permissions:
      actions: read
      pull-requests: write
    needs: []
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          additional_args: "--force-all-dirs --concise-output --code-theme=dark"
          version: "latest"
          github_token: ${{ github.token }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@12
        with:
          directory: .
          framework: terraform